from top5_markov_holiday_recommendation import *
from test_cases import *

create_main_table.__doc__ = """
Description
-----------
This function is used to create a consolidated main table by loading and merging
multiple datasets related to tourism in Indonesia. The resulting table provides a
comprehensive view of user reviews, location details, and additional attributes
for tourism places in Indonesia.

Returns
-------
The function returns a Pandas DataFrame, which is the consolidated main table
containing user reviews, location details, and relevant attributes for tourism
places in Indonesia.
"""

create_probability_table.__doc__ = """
Description
-----------
This function is used to create a probability table that calculates the likelihood
of a user with a given history to visit places of various categories in Indonesia.
The probability table is generated based on user historical data and place category ratings.

Arguments
---------
user            The unique identifier of the user for whom the probability table is created.
main_table      The main table containing user reviews, location details, and relevant
                attributes for tourism places in Indonesia.

Returns
-------
The function returns a Pandas DataFrame, user_probability_table, containing information
about the user's historical visits, category counts, average ratings, and the calculated
probabilities for visiting places in different categories.
"""

create_transition_matrix.__doc__ = """
Description
-----------
This function is used to create tansition matrix that models the probability of the user's 
transition from one place category to another. tansition matrix is calculated based on user's historical 
data and probabilities associated with visiting different place category.  

Arguments
-----------
user            The unique identifier of the user for whom the transition matrix is created.
main_table      The main table contains user reviews, location details, and relevant
                attributes for tourism places in Indonesia.

Returns
------------
This function returns Pandas DataFrame, tansition_matrix which representing the probabilities
of the transition from one place category to another. it is useful for modeling user behavior
and recomending frequently visited place category based on user historical visits in Indonesia.
"""

recommend_category.__doc__ = """
Description
-----------
This function is used to recommend the new category according to the user's current catrgory
interest. it taking the transition probabilities within the matrix for new suggestion of the category
that user may find interesting.

Arguments
---------
user                The unique identifier of the user for whom the category recommendation is generated.
category            The current category of users interested in and from there seeking new
                    recommendations for a category.
transition_matrix   This is Pandas DataFrame containing the transition probabilities between
                    different place categories. it is generated by create_transition_matrix function

Returns
-------
It is returning the new category as string for user as next explore cetegory. it is recommending
a category based on the user's current category and transition matrix.
"""  

create_rating_by_age_table.__doc__ = """
Description
-----------
This function is used to create_rating_by_age_table that aggregates and calculates the average rating
of place for the specific city by categorising user age range. This table give information of popularity
and quality of these place by age group.

Arguments
---------
city            The city name for which rating age table generated.
main_table      The main table contains user reviews, location details, and relevant
                attributes for tourism places in Indonesia.

Returns
--------
The function returns Pandas DataFrame rating_by_age_table which containg average rating of place for 
specific city, categorised by user age group. providing insight of popularity and quality of the
place among different user age group.
"""  

create_user_history.__doc__= """
Description
-----------
This function is used to create_user_history based on the history of the places visited
by specific user. this function is depending on the user has visitation history or not.

Arguments
---------
user            The unique identifier of the user for whom the visited history retrived.
main_table      The main table contains user reviews, location details, and relevant
                attributes for tourism places in Indonesia.
Returns
-------
This function return the list of Place_Id visited by the specific user otherwise an empty list
if no user visited the place.
"""

recommend_place.__doc__= """
Description
-----------
This function is used to recommend the place to the user who are seeking for based on the
user unique identifier, user age range, and new place that user interested in and also with or
without user visited history.

Arguments
---------
user            The unique identifier of the user for whom the recommendation is generated
category        The category for which user looking for recommendation.
city            The city for which recommendations are made.
main_table      The main table contains user reviews, location details, and relevant
                attributes for tourism places in Indonesia.
rating_by_age   rating_by_age table created by create_rating_by_age_table function.
user_history    The list of place_Id based on user visited history.

Returns
--------
This function returns the recommended places in dictionary with place has its ID and name.
"""

run_program.__doc__= """
Description
-----------
This function is used as generating place recommendation system to the specific user based on the
user interest and user history. it calls all the function defined.

Arguments
---------

user            The unique identifier user for whom seeking for place recommendation.
main_table      The main table contains user reviews, location details, and relevant
                attributes for tourism places in Indonesia.
category        The initial category that user prefrence.
city            The city name for which recommendations are provided.

Returns
--------
The function returns the recommended category in tuple and the top 5 recommended place
in dictionary for the specific user.
"""